name: regression test on demand
on: [workflow_dispatch]
jobs:
  regression-on-demand:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.5
      - name: install dependencies
        run: npm install
      - name: cypress execution
        run: npx cypress run
      - name: Generate test artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            allure-results/
            cypress/reports/
            cypress/screenshots/
